export const Render = [
    {
        type: "Bio",
        name: "Zachary Lee",
        title: "SWE",
        portfolioPurpose: "Fun",
        socialLinks: ["https://github.com/zacharyLYH"],
        tldr: "My tldr",
        aboutMe: "My about me",
        image: "/vercel.svg",
        hobbies: ["cooking", "games"],
    },
    {
        type: "Project",
        name: "swe1",
        summary: "learned a lot",
        skills: ["golang", "nodejs"],
        story: "dasonfds",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        featured: true,
        dateStartToEnd: "1/1 - 2/1",
    },
    {
        type: "Project",
        name: "swe2",
        summary: "learned a lot2",
        skills: ["golang", "nodejs"],
        story: "dasonfd2sss",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "learned a lot2",
        skills: ["golang", "nodejs"],
        story: "dasonfd2ers",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Project",
        name: "swe2",
        summary: "learned a lot2",
        skills: ["golang", "nodejs"],
        story: "dasonwerfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Project",
        name: "swe2",
        summary: "learned a lot2",
        skills: ["golang", "nodejs"],
        story: "dasongnfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Project",
        name: "swe2",
        summary: "learned a lot2",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summary",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2saaaa",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        orgName: "hello",
        dateStartEnd:"1/1-2/1"
    },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summarysdf",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2sbbbbbb",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        orgName: "hello",
    },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summaryere",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2scccccccc",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        orgName: "hello",
    },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summary123",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        orgName: "hello",
    },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summaryss",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        orgName: "hello",
        dateStartEnd:"1/1-2/1"
    },
];
