export const Render = [
    {
        type: "Bio",
        name: "Zachary Lee",
        title: "SWE",
        portfolioPurpose: "Fun",
        socialLinks: [
            "https://github.com/zacharyLYH",
            "www.linkedin.com/in/zacharyleeyh",
            "leeyihong03@gmail.com",
        ],
        tldr: "My tldr My tldr My tldr My tldr My tldr My tldr My tldr My tldr",
        aboutMe:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ut sem viverra aliquet eget sit amet tellus. Morbi non arcu risus quis varius quam. Tempor commodo ullamcorper a lacus vestibulum. Facilisis mauris sit amet massa vitae tortor condimentum. Nam libero justo laoreet sit amet cursus sit amet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Tellus mauris a diam maecenas sed enim. Lobortis feugiat vivamus at augue eget. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc.Porttitor leo a diam sollicitudin tempor id eu. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Feugiat vivamus at augue eget. Fermentum odio eu feugiat pretium nibh ipsum consequat. Eget arcu dictum varius duis at consectetur lorem. Mi ipsum faucibus vitae aliquet. Donec massa sapien faucibus et molestie. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Augue ut lectus arcu bibendum at varius vel pharetra vel. Quis viverra nibh cras pulvinar mattis. Egestas maecenas pharetra convallis posuere morbi. Sem viverra aliquet eget sit amet tellus cras adipiscing. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Lobortis scelerisque fermentum dui faucibus in ornare quam. Adipiscing enim eu turpis egestas pretium. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Amet massa vitae tortor condimentum lacinia.Neque laoreet suspendisse interdum consectetur libero id. Odio ut sem nulla pharetra diam sit amet nisl suscipit. Mauris rhoncus aenean vel elit scelerisque mauris. Mauris sit amet massa vitae. Ullamcorper a lacus vestibulum sed arcu non odio. Sed sed risus pretium quam vulputate dignissim suspendisse in. Fermentum dui faucibus in ornare quam. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Mauris augue neque gravida in fermentum et. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Id velit ut tortor pretium viverra suspendisse potenti nullam. Sit amet mauris commodo quis. Fames ac turpis egestas maecenas.Ultrices mi tempus imperdiet nulla. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Imperdiet dui accumsan sit amet nulla. Mattis pellentesque id nibh tortor id aliquet. Sodales ut eu sem integer vitae. Quis eleifend quam adipiscing vitae proin. Eget nunc scelerisque viverra mauris. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Nam aliquam sem et tortor consequat id. Ultrices vitae auctor eu augue utFringilla urna porttitor rhoncus dolor purus non enim. Maecenas ultricies mi eget mauris pharetra et ultrices. Sagittis vitae et leo duis ut diam. At auctor urna nunc id cursus. Cras fermentum odio eu feugiat pretium nibh ipsum. Viverra adipiscing at in tellus integer feugiat scelerisque varius. Gravida cum sociis natoque penatibus. Purus semper eget duis at. Tristique senectus et netus et malesuada fames ac turpis egestas. Est ante in nibh mauris cursus mattis. Arcu non odio euismod lacinia at quis risus sed. Luctus venenatis lectus magna fringilla urna porttitor. Amet facilisis magna etiam tempor.",
        image: "/headshot.jpeg",
        hobbies: [
            "cooking",
            "games",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At tellus at urna condimentum mattis pellentesque id nibh. Et ligula ullamcorper malesuada proin. Libero justo laoreet sit amet cursus sit amet dictum. Lacus laoreet non curabitur gravida arcu. Eu lobortis elementum nibh tellus molestie nunc non. Montes nascetur ridiculus mus mauris vitae. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Ut etiam sit amet nisl. Turpis egestas maecenas pharetra convallis posuere. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Lacinia at quis risus sed vulputate odio ut enim. Commodo viverra maecenas accumsan lacus. Duis at consectetur lorem donec massa sapien faucibus. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Consequat ac felis donec et odio pellentesque diam. At varius vel pharetra vel turpis nunc eget lorem. Libero nunc consequat interdum varius sit amet mattis. Diam donec adipiscing tristique risus nec.",
        ],
        jobStatus: "Interview Ready",
    },
    {
        type: "Project",
        name: "swe1",
        summary:
            "learned a lotlearned a lotlearned a lotlearned a lotlearned a lotlearned a lotlearned a lotlearned a lotlearned a lotlearned a lotlearned a lotlearned a lot",
        skills: ["golang", "nodejs"],
        story: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At tellus at urna condimentum mattis pellentesque id nibh. Et ligula ullamcorper malesuada proin. Libero justo laoreet sit amet cursus sit amet dictum. Lacus laoreet non curabitur gravida arcu. Eu lobortis elementum nibh tellus molestie nunc non. Montes nascetur ridiculus mus mauris vitae. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Ut etiam sit amet nisl. Turpis egestas maecenas pharetra convallis posuere. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Lacinia at quis risus sed vulputate odio ut enim. Commodo viverra maecenas accumsan lacus. Duis at consectetur lorem donec massa sapien faucibus. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Consequat ac felis donec et odio pellentesque diam. At varius vel pharetra vel turpis nunc eget lorem. Libero nunc consequat interdum varius sit amet mattis. Diam donec adipiscing tristique risus nec.",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        featured: true,
        dateStartToEnd: "1/1 - 2/1",
    },
    {
        type: "Project",
        name: "swe2",
        summary: "a",
        skills: ["golang", "nodejs"],
        story: "dasonsssfd2sxxss",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "b",
        skills: ["golang", "nodejs"],
        story: "dasonsssfd2ssszczca",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "c",
        skills: ["golang", "nodejs"],
        story: "dasonsssfd2bvcbsss",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "d",
        skills: ["golang", "nodejs"],
        story: "dasonsssfd2sssdfs",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "e",
        skills: ["golang", "nodejs"],
        story: "dasonsssfdrgr22sss",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "f",
        skills: ["golang", "nodejs"],
        story: "dasonsssfd2sssll",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "g",
        skills: ["golang", "nodejs"],
        story: "dasonssnnnnsfd2sss",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        featured: true,
    },
    {
        type: "Project",
        name: "swe2",
        summary: "h",
        skills: ["golang", "nodejs"],
        story: "dasonwerfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Project",
        name: "swe2",
        summary: "i",
        skills: ["golang", "nodejs"],
        story: "dasongnfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Project",
        name: "swe2",
        summary: "j",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfsdfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Project",
        name: "swe2",
        summary: "k",
        skills: ["golang", "nodejs"],
        story: "dasoxx111nfsdfd2s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    {
        type: "Project",
        name: "swe2",
        summary: "l",
        skills: ["golang", "nodejs"],
        story: "dasoxx111nfsdfd2m88s",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    },
    // {
    //     type: "Project",
    //     name: "swe2",
    //     summary: "l",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxx111nfsdfd28b8s",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    // },
    // {
    //     type: "Project",
    //     name: "swe2",
    //     summary: "l",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxx111nfsdfd2i88s",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    // },
    // {
    //     type: "Project",
    //     name: "swe2",
    //     summary: "l",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxx111nfsdfd2u88s",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    // },
    // {
    //     type: "Project",
    //     name: "swe2",
    //     summary: "l",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxx111nfsdfd288ls",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    // },
    // {
    //     type: "Project",
    //     name: "swe2",
    //     summary: "l",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxx111nfsdfd288s",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    // },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summary",
        skills: ["golang", "nodejs"],
        story: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ut sem viverra aliquet eget sit amet tellus. Morbi non arcu risus quis varius quam. Tempor commodo ullamcorper a lacus vestibulum. Facilisis mauris sit amet massa vitae tortor condimentum. Nam libero justo laoreet sit amet cursus sit amet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Tellus mauris a diam maecenas sed enim. Lobortis feugiat vivamus at augue eget. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc.Porttitor leo a diam sollicitudin tempor id eu. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Feugiat vivamus at augue eget. Fermentum odio eu feugiat pretium nibh ipsum consequat. Eget arcu dictum varius duis at consectetur lorem. Mi ipsum faucibus vitae aliquet. Donec massa sapien faucibus et molestie. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Augue ut lectus arcu bibendum at varius vel pharetra vel. Quis viverra nibh cras pulvinar mattis. Egestas maecenas pharetra convallis posuere morbi. Sem viverra aliquet eget sit amet tellus cras adipiscing. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Lobortis scelerisque fermentum dui faucibus in ornare quam. Adipiscing enim eu turpis egestas pretium. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Amet massa vitae tortor condimentum lacinia.Neque laoreet suspendisse interdum consectetur libero id. Odio ut sem nulla pharetra diam sit amet nisl suscipit. Mauris rhoncus aenean vel elit scelerisque mauris. Mauris sit amet massa vitae. Ullamcorper a lacus vestibulum sed arcu non odio. Sed sed risus pretium quam vulputate dignissim suspendisse in. Fermentum dui faucibus in ornare quam. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Mauris augue neque gravida in fermentum et. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Id velit ut tortor pretium viverra suspendisse potenti nullam. Sit amet mauris commodo quis. Fames ac turpis egestas maecenas.Ultrices mi tempus imperdiet nulla. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Imperdiet dui accumsan sit amet nulla. Mattis pellentesque id nibh tortor id aliquet. Sodales ut eu sem integer vitae. Quis eleifend quam adipiscing vitae proin. Eget nunc scelerisque viverra mauris. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Nam aliquam sem et tortor consequat id. Ultrices vitae auctor eu augue utFringilla urna porttitor rhoncus dolor purus non enim. Maecenas ultricies mi eget mauris pharetra et ultrices. Sagittis vitae et leo duis ut diam. At auctor urna nunc id cursus. Cras fermentum odio eu feugiat pretium nibh ipsum. Viverra adipiscing at in tellus integer feugiat scelerisque varius. Gravida cum sociis natoque penatibus. Purus semper eget duis at. Tristique senectus et netus et malesuada fames ac turpis egestas. Est ante in nibh mauris cursus mattis. Arcu non odio euismod lacinia at quis risus sed. Luctus venenatis lectus magna fringilla urna porttitor. Amet facilisis magna etiam tempor.",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        orgName: "hello",
        dateStartEnd: "1/1-2/1",
    },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summarysdf",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2sbbbbbb",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        orgName: "hello",
    },
    {
        type: "Experience",
        title: "swe2",
        summary: "experience summaryere",
        skills: ["golang", "nodejs"],
        story: "dasoxxnfd2scccccccc",
        links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
        current: true,
        orgName: "hello",
    },
    {
        type: "Footer",
        author: "John Smith",
        links: ["https://github.com/zacharyLYH"],
    },
    // {
    //     type: "Experience",
    //     title: "swe2",
    //     summary: "experience summary123",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxxnfd2s",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    //     current: true,
    //     orgName: "hello",
    // },
    // {
    //     type: "Experience",
    //     title: "swe2",
    //     summary: "experience summaryss",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxxnfd2s",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    //     current: true,
    //     orgName: "hello",
    //     dateStartEnd:"1/1-2/1"
    // },
    // {
    //     type: "Experience",
    //     title: "swe2",
    //     summary: "experience summaryss",
    //     skills: ["golang", "nodejs"],
    //     story: "dasoxxnfdaaaa2s",
    //     links: ["https://github.com/cse442-at-ub/project_s23-p-np/tree/dev"],
    //     current: true,
    //     orgName: "hello",
    //     dateStartEnd:"1/1-2/1"
    // },
];
